version: '3'

services:
  web:
    build: .
    command: >
      /bin/bash -c "
        python run.py;
        python rabbitmq_folder/consumer.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/file_generation_repo
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbit_start.sh