version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    labels:
      NAME: "rabbitmq"

  web:
    build: .
    command: bash -c "export PYTHONPATH="${PYTHONPATH}:/file_generation_service_repo" && supervisord -c supervisord.conf && python3 run.py"
    volumes:
      - .:/file_generation_service_repo
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started