version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=vhost
#    volumes:
#    - ./rabbit_start.sh:/init.sh

  web:
    build: .
    command: bash -c "supervisord -c supervisord.conf && python3 run.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/file_generation_service_repo
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
